/* Allegro datafile object indexes, produced by grabber v4.1.9 (WIP), djgpp */
/* Datafile: c:\zc\eb_fonts.dat */
/* Date: Tue Jun 24 00:19:45 2003 */
/* Do not hand edit! */

#define FONT_6x6                         0                  /* FONT */
#define FONT_8xPROP                      1                  /* FONT */
#define FONT_COMIC                       2                  /* FONT */
#define FONT_GUI                         3                  /* FONT */
#define FONT_LARGEFIXED                  4                  /* FONT */
#define FONT_LARGEPROP                   5                  /* FONT */
#define FONT_Z3                          6                  /* FONT */
#define PAL_EB_TEST                      7                  /* PAL  */
