/* Allegro datafile object indexes, produced by grabber v4.2.0, MinGW32 */
/* Datafile: c:\zc\fonts.dat */
/* Date: Thu Apr 13 10:44:03 2006 */
/* Do not hand edit! */

#define _SIGNATURE                       0        /* DATA */
#define FONT_6x6                         1        /* FONT */
#define FONT_6xPROP                      2        /* FONT */
#define FONT_8xPROP_THIN                 3        /* FONT */
#define FONT_GBZELDA                     4        /* FONT */
#define FONT_GORON                       5        /* FONT */
#define FONT_GUI_MONO                    6        /* FONT */
#define FONT_GUI_PROP                    7        /* FONT */
#define FONT_HYLIAN1                     8        /* FONT */
#define FONT_HYLIAN2                     9        /* FONT */
#define FONT_HYLIAN3                     10       /* FONT */
#define FONT_HYLIAN4                     11       /* FONT */
#define FONT_LARGEFIXED                  12       /* FONT */
#define FONT_LARGEPROP                   13       /* FONT */
#define FONT_LARGEPROP_L                 14       /* FONT */
#define FONT_MATRIX                      15       /* FONT */
#define FONT_NES                         16       /* FONT */
#define FONT_SUBSCREEN1                  17       /* FONT */
#define FONT_SUBSCREEN2                  18       /* FONT */
#define FONT_SUBSCREEN3                  19       /* FONT */
#define FONT_SUBSCREEN4                  20       /* FONT */
#define FONT_Z3                          21       /* FONT */
#define FONT_Z3SMALL                     22       /* FONT */
#define FONT_ZORAN                       23       /* FONT */
#define FONT_ZTIME                       24       /* FONT */

