/* Allegro datafile object indexes, produced by grabber v4.2.0, MinGW32 */
/* Datafile: c:\zc\fonts.dat */
/* Date: Wed Sep 13 13:42:20 2006 */
/* Do not hand edit! */

#define _SIGNATURE                       0        /* DATA */
#define FONT_6x4                         1        /* FONT */
#define FONT_6x6                         2        /* FONT */
#define FONT_6xPROP                      3        /* FONT */
#define FONT_8xPROP_THIN                 4        /* FONT */
#define FONT_GBZELDA                     5        /* FONT */
#define FONT_GORON                       6        /* FONT */
#define FONT_GUI_MONO                    7        /* FONT */
#define FONT_GUI_PROP                    8        /* FONT */
#define FONT_HYLIAN1                     9        /* FONT */
#define FONT_HYLIAN2                     10       /* FONT */
#define FONT_HYLIAN3                     11       /* FONT */
#define FONT_HYLIAN4                     12       /* FONT */
#define FONT_LARGEFIXED                  13       /* FONT */
#define FONT_LARGEPROP                   14       /* FONT */
#define FONT_LARGEPROP_L                 15       /* FONT */
#define FONT_MATRIX                      16       /* FONT */
#define FONT_NES                         17       /* FONT */
#define FONT_SUBSCREEN1                  18       /* FONT */
#define FONT_SUBSCREEN2                  19       /* FONT */
#define FONT_SUBSCREEN3                  20       /* FONT */
#define FONT_SUBSCREEN4                  21       /* FONT */
#define FONT_Z3                          22       /* FONT */
#define FONT_Z3SMALL                     23       /* FONT */
#define FONT_ZORAN                       24       /* FONT */
#define FONT_ZTIME                       25       /* FONT */

