/* Allegro datafile object indexes, produced by grabber v4.2.0, MacOS X */
/* Datafile: /zc/trunk/sfx.dat */
/* Date: Wed Oct 18 20:33:22 2006 */
/* Do not hand edit! */

#define _SIGNATURE                       0        /* DATA */
#define WAV_ARROW                        1        /* SAMP */
#define WAV_BEAM                         2        /* SAMP */
#define WAV_BOMB                         3        /* SAMP */
#define WAV_BRANG                        4        /* SAMP */
#define WAV_CHIME                        5        /* SAMP */
#define WAV_CHINK                        6        /* SAMP */
#define WAV_CLEARED                      7        /* SAMP */
#define WAV_DINSFIRE                     8        /* SAMP */
#define WAV_DODONGO                      9        /* SAMP */
#define WAV_DOOR                         10       /* SAMP */
#define WAV_EDEAD                        11       /* SAMP */
#define WAV_EHIT                         12       /* SAMP */
#define WAV_ER                           13       /* SAMP */
#define WAV_FARORESWIND                  14       /* SAMP */
#define WAV_FIRE                         15       /* SAMP */
#define WAV_FIREBALL                     16       /* SAMP */
#define WAV_GANON                        17       /* SAMP */
#define WAV_GASP                         18       /* SAMP */
#define WAV_GRASSCUT                     19       /* SAMP */
#define WAV_HAMMER                       20       /* SAMP */
#define WAV_HAMMERPOST                   21       /* SAMP */
#define WAV_HOOKSHOT                     22       /* SAMP */
#define WAV_HOVER                        23       /* SAMP */
#define WAV_JUMP                         24       /* SAMP */
#define WAV_LENSOFF                      25       /* SAMP */
#define WAV_LENSON                       26       /* SAMP */
#define WAV_MSG                          27       /* SAMP */
#define WAV_NAYRUSLOVE1                  28       /* SAMP */
#define WAV_NAYRUSLOVE2                  29       /* SAMP */
#define WAV_OUCH                         30       /* SAMP */
#define WAV_PICKUP                       31       /* SAMP */
#define WAV_PLACE                        32       /* SAMP */
#define WAV_PLINK                        33       /* SAMP */
#define WAV_PUSHBLOCK                    34       /* SAMP */
#define WAV_REFILL                       35       /* SAMP */
#define WAV_ROAR                         36       /* SAMP */
#define WAV_ROCKETDOWN                   37       /* SAMP */
#define WAV_ROCKETUP                     38       /* SAMP */
#define WAV_SCALE                        39       /* SAMP */
#define WAV_SEA                          40       /* SAMP */
#define WAV_SECRET                       41       /* SAMP */
#define WAV_SPIRAL                       42       /* SAMP */
#define WAV_SPLASH                       43       /* SAMP */
#define WAV_STAIRS                       44       /* SAMP */
#define WAV_SWORD                        45       /* SAMP */
#define WAV_VADER                        46       /* SAMP */
#define WAV_WAND                         47       /* SAMP */
#define WAV_WHISTLE                      48       /* SAMP */
#define WAV_ZELDA                        49       /* SAMP */
#define Z35                              50       /* SAMP */


