#include "SymbolDefs.h"

DMapDataSymbols DMapDataSymbols::singleton = DMapDataSymbols();

static AccessorTable DMapDataTable[] =
{
//	All of these return a function label error when used:
//	  name,                     rettype,                  setorget,     var,                        numindex,      funcFlags,                            numParams,   params
	{ "getTest",                ZVARTYPEID_FLOAT,         GETTER,       DEBUGREFFFC,                1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "GetName",                ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "SetName",                ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "GetTitle",               ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "SetTitle",               ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "GetIntro",               ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "SetIntro",               ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "GetMusic",               ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "SetMusic",               ZVARTYPEID_VOID,          FUNCTION,     0,                          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	//
	{ "getID",                  ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAID,                 1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMap",                 ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAMAP,                1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMap",                 ZVARTYPEID_VOID,          SETTER,       DMAPDATAMAP,                1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getLevel",               ZVARTYPEID_FLOAT,         GETTER,       DMAPDATALEVEL,              1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setLevel",               ZVARTYPEID_VOID,          SETTER,       DMAPDATALEVEL,              1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getOffset",              ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAOFFSET,             1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setOffset",              ZVARTYPEID_VOID,          SETTER,       DMAPDATAOFFSET,             1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getCompass",             ZVARTYPEID_FLOAT,         GETTER,       DMAPDATACOMPASS,            1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setCompass",             ZVARTYPEID_VOID,          SETTER,       DMAPDATACOMPASS,            1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getPalette",             ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAPALETTE,            1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setPalette",             ZVARTYPEID_VOID,          SETTER,       DMAPDATAPALETTE,            1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMIDI",                ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAMIDI,               1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMIDI",                ZVARTYPEID_VOID,          SETTER,       DMAPDATAMIDI,               1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getContinue",            ZVARTYPEID_FLOAT,         GETTER,       DMAPDATACONTINUE,           1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setContinue",            ZVARTYPEID_VOID,          SETTER,       DMAPDATACONTINUE,           1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getType",                ZVARTYPEID_FLOAT,         GETTER,       DMAPDATATYPE,               1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setType",                ZVARTYPEID_VOID,          SETTER,       DMAPDATATYPE,               1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getScript",              ZVARTYPEID_FLOAT,         GETTER,       DMAPSCRIPT,                 1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setScript",              ZVARTYPEID_VOID,          SETTER,       DMAPSCRIPT,                 1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMusicTrack",          ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAMUISCTRACK,         1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMusicTrack",          ZVARTYPEID_VOID,          SETTER,       DMAPDATAMUISCTRACK,         1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getActiveSubscreen",     ZVARTYPEID_FLOAT,         GETTER,       DMAPDATASUBSCRA,            1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setActiveSubscreen",     ZVARTYPEID_VOID,          SETTER,       DMAPDATASUBSCRA,            1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getPassiveSubscreen",    ZVARTYPEID_FLOAT,         GETTER,       DMAPDATASUBSCRP,            1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setPassiveSubscreen",    ZVARTYPEID_VOID,          SETTER,       DMAPDATASUBSCRP,            1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
//	{ "getGravity[]",           ZVARTYPEID_FLOAT,         GETTER,       DMAPDATASUBSCRP,            1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
//	{ "setGravity[]",           ZVARTYPEID_VOID,          SETTER,       DMAPDATASUBSCRP,            1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
//	{ "getJumpThreshold",       ZVARTYPEID_FLOAT,         GETTER,       DMAPDATASUBSCRP,            1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
//	{ "setJumpThreshold",       ZVARTYPEID_VOID,          SETTER,       DMAPDATASUBSCRP,            1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getGrid[]",              ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAGRID,               8,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setGrid[]",              ZVARTYPEID_VOID,          SETTER,       DMAPDATAGRID,               8,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMiniMapTile[]",       ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAMINIMAPTILE,        2,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMiniMapTile[]",       ZVARTYPEID_VOID,          SETTER,       DMAPDATAMINIMAPTILE,        2,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMiniMapCSet[]",       ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAMINIMAPCSET,        2,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMiniMapCSet[]",       ZVARTYPEID_VOID,          SETTER,       DMAPDATAMINIMAPCSET,        2,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	
	{ "getInitD[]",             ZVARTYPEID_FLOAT,         GETTER,       DMAPINITD,                  8,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setInitD[]",             ZVARTYPEID_VOID,          SETTER,       DMAPINITD,                  8,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMapTile[]",           ZVARTYPEID_FLOAT,         GETTER,       DMAPDATALARGEMAPTILE,       2,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMapTile[]",           ZVARTYPEID_VOID,          SETTER,       DMAPDATALARGEMAPTILE,       2,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMapCSet[]",           ZVARTYPEID_FLOAT,         GETTER,       DMAPDATALARGEMAPCSET,       2,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMapCSet[]",           ZVARTYPEID_VOID,          SETTER,       DMAPDATALARGEMAPCSET,       2,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getDisabledItems[]",     ZVARTYPEID_FLOAT,         GETTER,       DMAPDATADISABLEDITEMS,      256,           0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setDisabledItems[]",     ZVARTYPEID_VOID,          SETTER,       DMAPDATADISABLEDITEMS,      256,           0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getFlags",               ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAFLAGS,              1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setFlags",               ZVARTYPEID_VOID,          SETTER,       DMAPDATAFLAGS,              1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getFlagset[]",     ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAFLAGARR,      32,           0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setFlagset[]",     ZVARTYPEID_VOID,          SETTER,       DMAPDATAFLAGARR,      32,           0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	
	{ "getSideview",            ZVARTYPEID_BOOL,          GETTER,       DMAPDATASIDEVIEW,           1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setSideview",            ZVARTYPEID_VOID,          SETTER,       DMAPDATASIDEVIEW,           1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_BOOL, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	
	{ "getASubScript",          ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAASUBSCRIPT,         1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },      
	{ "setASubScript",          ZVARTYPEID_VOID,          SETTER,       DMAPDATAASUBSCRIPT,         1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getPSubScript",          ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAPSUBSCRIPT,         1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },      
	{ "setPSubScript",          ZVARTYPEID_VOID,          SETTER,       DMAPDATAPSUBSCRIPT,         1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getSubInitD[]",          ZVARTYPEID_UNTYPED,       GETTER,       DMAPDATASUBINITD,           8,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setSubInitD[]",          ZVARTYPEID_VOID,          SETTER,       DMAPDATASUBINITD,           8,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_UNTYPED, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMapScript",           ZVARTYPEID_FLOAT,         GETTER,       DMAPDATAMAPSCRIPT,          1,             0,                                    1,           { ZVARTYPEID_DMAPDATA, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },      
	{ "setMapScript",           ZVARTYPEID_VOID,          SETTER,       DMAPDATAMAPSCRIPT,          1,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getMapInitD[]",          ZVARTYPEID_UNTYPED,       GETTER,       DMAPDATAMAPINITD,           8,             0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setMapInitD[]",          ZVARTYPEID_VOID,          SETTER,       DMAPDATAMAPINITD,           8,             0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_UNTYPED, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "getCharted[]",           ZVARTYPEID_FLOAT,         GETTER,       DMAPDATACHARTED,            128,           0,                                    2,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	{ "setCharted[]",           ZVARTYPEID_VOID,          SETTER,       DMAPDATACHARTED,            128,           0,                                    3,           { ZVARTYPEID_DMAPDATA, ZVARTYPEID_FLOAT, ZVARTYPEID_FLOAT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } },
	
	{ "",                       -1,                       -1,           -1,                         -1,            0,                                    0,           { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 } }
};

DMapDataSymbols::DMapDataSymbols()
{
    table = DMapDataTable;
    refVar = REFDMAPDATA;
}

void DMapDataSymbols::generateCode()
{
}

