server {
    listen      80;
    server_name docs.zquestclassic.com;
    return 301 https://docs.zquestclassic.com$request_uri;
}

server {
    server_name docs.zquestclassic.com;
    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/docs.zquestclassic.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/docs.zquestclassic.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    root /var/www/docs.zquestclassic.com;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Custom error page for 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
