
//ri->mapsref = ID;

MAPDATAVALID //b
MAPDATAGUY //b
MAPDATASTRING //w
MAPDATAROOM //b
MAPDATAITEM //b
MAPDATAHASITEM //b
MAPDATATILEWARPTYPE //b, 4 of these
MAPDATATILEWARPOVFLAGS //b, tilewarpoverlayflags
MAPDATADOORCOMBOSET //w
MAPDATAWARPRETX //b, 4 of these
MAPDATAWARPRETY //b, 4 of these
MAPDATAWARPRETURNC //w
MAPDATASTAIRX //b
MAPDATASTAIRY //b
MAPDATACOLOUR //w
MAPDATAENEMYFLAGS //b
MAPDATADOOR //b, 4 of these
MAPDATATILEWARPDMAP //w, 4 of these
MAPDATATILEWARPSCREEN //b, 4 of these
MAPDATAEXITDIR //b
MAPDATAENEMY //w, 10 of these
MAPDATAPATTERN //b
MAPDATASIDEWARPTYPE //b, 4 of these
MAPDATASIDEWARPOVFLAGS //b
MAPDATAWARPARRIVALX //b
MAPDATAWARPARRIVALY //b
MAPDATAPATH //b, 4 of these
MAPDATASIDEWARPSC //b, 4 of these
MAPDATASIDEWARPDMAP //w, 4 of these
MAPDATASIDEWARPINDEX //b
MAPDATAUNDERCOMBO //w
MAPDATAUNDERCSET //b
MAPDATACATCHALL //W
MAPDATAFLAGS //B, 11 OF THESE, flags, flags2-flags10
MAPDATACSENSITIVE //B
MAPDATANORESET //W
MAPDATANOCARRY //W
MAPDATALAYERMAP //B, 6 OF THESE
MAPDATALAYERSCREEN //B, 6 OF THESE
MAPDATALAYEROPACITY //B, 6 OF THESE
MAPDATATIMEDWARPTICS //W
MAPDATANEXTMAP //B
MAPDATANEXTSCREEN //B
MAPDATASECRETCOMBO //W, 128 OF THESE
MAPDATASECRETCSET //B, 128 OF THESE
MAPDATASECRETFLAG //B, 128 OF THESE
MAPDATAVIEWX //W
MAPDATAVIEWY //W
MAPDATASCREENWIDTH //B
MAPDATASCREENHEIGHT //B
MAPDATAENTRYX //B
MAPDATAENTRYY //B
MAPDATANUMFF //INT16
MAPDATAFFDATA //W, 32 OF THESE
MAPDATAFFCSET //B, 32
MAPDATAFFDELAY //W, 32
MAPDATAFFX //INT32, 32 OF THESE
MAPDATAFFY //..
MAPDATAFFXDELTA //..
MAPDATAFFYDELTA //..
MAPDATAFFXDELTA2 //..
MAPDATAFFYDELTA2 //..
MAPDATAFFFLAGS //INT16, 23 OF THESE
MAPDATAFFWIDTH //B, 32 OF THESE
MAPDATAFFHEIGHT //B, 32 OF THESE
MAPDATAFFLINK //B, 32 OF THESE
MAPDATAFFSCRIPT //W, 32 OF THESE
MAPDATAINTID //INT32 , 32 OF THESE, EACH WITH 10 INDICES. 
MAPDATAINITA //INT32, 32 OF THESE, EACH WITH 2
MAPDATAFFINITIALISED //BOOL, 32 OF THESE
MAPDATASCRIPTENTRY //W
MAPDATASCRIPTOCCUPANCY //W
MAPDATASCRIPTEXIT //W
MAPDATAOCEANSFX //B
MAPDATABOSSSFX //B
MAPDATASECRETSFX //B
MAPDATAHOLDUPSFX //B
MAPDATASCREENMIDI //SHORT, OLD QUESTS ONLY?
MAPDATALENSLAYER //B, OLD QUESTS ONLY?