SCREENDATAVALID //b
SCREENDATAGUY //b
SCREENDATASTRING //w
SCREENDATAROOM //b
SCREENDATAITEM //b
SCREENDATAHASITEM //b
SCREENDATATILEWARPTYPE //b, 4 of these
SCREENDATATILEWARPOVFLAGS //b, tilewarpoverlayflags
SCREENDATADOORCOMBOSET //w
SCREENDATAWARPRETX //b, 4 of these
SCREENDATAWARPRETY //b, 4 of these
SCREENDATAWARPRETURNC //w
SCREENDATASTAIRX //b
SCREENDATASTAIRY //b
SCREENDATACOLOUR //w
SCREENDATAENEMYFLAGS //b
SCREENDATADOOR //b, 4 of these
SCREENDATATILEWARPDMAP //w, 4 of these
SCREENDATATILEWARPSCREEN //b, 4 of these
SCREENDATAEXITDIR //b
SCREENDATAENEMY //w, 10 of these
SCREENDATAPATTERN //b
SCREENDATASIDEWARPTYPE //b, 4 of these
SCREENDATASIDEWARPOVFLAGS //b
SCREENDATAWARPARRIVALX //b
SCREENDATAWARPARRIVALY //b
SCREENDATAPATH //b, 4 of these
SCREENDATASIDEWARPSC //b, 4 of these
SCREENDATASIDEWARPDMAP //w, 4 of these
SCREENDATASIDEWARPINDEX //b
SCREENDATAUNDERCOMBO //w
SCREENDATAUNDERCSET //b
SCREENDATACATCHALL //W
SCREENDATAFLAGS //B, 11 OF THESE, flags, flags2-flags10
SCREENDATACSENSITIVE //B
SCREENDATANORESET //W
SCREENDATANOCARRY //W
SCREENDATALAYERMAP //B, 6 OF THESE
SCREENDATALAYERSCREEN //B, 6 OF THESE
SCREENDATALAYEROPACITY //B, 6 OF THESE
SCREENDATATIMEDWARPTICS //W
SCREENDATANEXTMAP //B
SCREENDATANEXTSCREEN //B
SCREENDATASECRETCOMBO //W, 128 OF THESE
SCREENDATASECRETCSET //B, 128 OF THESE
SCREENDATASECRETFLAG //B, 128 OF THESE
SCREENDATAVIEWX //W
SCREENDATAVIEWY //W
SCREENDATASCREENWIDTH //B
SCREENDATASCREENHEIGHT //B
SCREENDATAENTRYX //B
SCREENDATAENTRYY //B
SCREENDATANUMFF //INT16
SCREENDATAFFDATA //W, 32 OF THESE
SCREENDATAFFCSET //B, 32
SCREENDATAFFDELAY //W, 32
SCREENDATAFFX //INT32, 32 OF THESE
SCREENDATAFFY //..
SCREENDATAFFXDELTA //..
SCREENDATAFFYDELTA //..
SCREENDATAFFXDELTA2 //..
SCREENDATAFFYDELTA2 //..
SCREENDATAFFFLAGS //INT16, 23 OF THESE
SCREENDATAFFWIDTH //B, 32 OF THESE
SCREENDATAFFHEIGHT //B, 32 OF THESE
SCREENDATAFFLINK //B, 32 OF THESE
SCREENDATAFFSCRIPT //W, 32 OF THESE
SCREENDATAINTID //INT32 , 32 OF THESE, EACH WITH 10 INDICES. 
SCREENDATAINITA //INT32, 32 OF THESE, EACH WITH 2
SCREENDATAFFINITIALISED //BOOL, 32 OF THESE
SCREENDATASCRIPTENTRY //W
SCREENDATASCRIPTOCCUPANCY //W
SCREENDATASCRIPTEXIT //W
SCREENDATAOCEANSFX //B
SCREENDATABOSSSFX //B
SCREENDATASECRETSFX //B
SCREENDATAHOLDUPSFX //B
SCREENDATASCREENMIDI //SHORT, OLD QUESTS ONLY?
SCREENDATALENSLAYER //B, OLD QUESTS ONLY?