// Generated by tests/update_auto_script_tests.py

#include "auto/arrays.zs"
#include "auto/classes.zs"
#include "auto/garbage_collection.zs"
#include "auto/optional_params.zs"
#include "auto/scc.zs"
#include "auto/sprites.zs"
#include "auto/viewport.zs"
