// Generated by tests/update_auto_script_tests.py

#include "auto/bug_empty_constructor.zs"
#include "auto/bug_mod_int_min.zs"
#include "auto/bug_nested_class_constructors.zs"
#include "auto/bug_script_draw_error_logging.zs"
#include "auto/bug_unused_var_bad_opt.zs"
#include "auto/classes.zs"
#include "auto/combo_script_owned_clear.zs"
#include "auto/ffc_script_runner.zs"
#include "auto/init_scripts.zs"
#include "auto/instant_reload_on_death.zs"
#include "auto/std_unit.zs"
#include "auto/varargs.zs"
