"""Generates a `qr_*` value -> name table from the enum in src/core/qrs.h.

Run by CMake as part of the build; see the `qr_names` custom command. The generated
file references each constant by name, so a rule renamed or removed in qrs.h without
regenerating is a compile error rather than a silently stale table.

Usage: gen_qr_names.py <path to qrs.h> <output .cpp>
"""

import re
import sys

# The enum runs from the first rule to the qr_MAX terminator.
ENUM_START = "qr_SOLIDBLK"
ENUM_END = "qr_MAX"


def parse_rule_names(header_text):
    start = header_text.index(ENUM_START)
    end = header_text.index(ENUM_END, start)
    body = header_text[start:end]

    # Strip comments first: several rules carry /*DEPRECATED*/ markers, and the byte
    # boundary markers (`// 85`) would otherwise look like content.
    body = re.sub(r"/\*.*?\*/", " ", body, flags=re.S)
    body = re.sub(r"//[^\n]*", " ", body)

    names = re.findall(r"\bqr_[A-Za-z0-9_]+\b", body)
    if not names:
        raise SystemExit(
            "gen_qr_names.py: found no rules - has the enum in qrs.h moved?"
        )

    duplicates = {n for n in names if names.count(n) > 1}
    if duplicates:
        raise SystemExit(f"gen_qr_names.py: duplicate rules: {sorted(duplicates)}")

    return names


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)

    header_path, output_path = sys.argv[1], sys.argv[2]
    with open(header_path) as f:
        names = parse_rule_names(f.read())

    lines = [
        "// Generated by scripts/gen_qr_names.py from src/core/qrs.h. Do not edit.",
        "",
        '#include "core/qrs.h"',
        "",
        "#include <array>",
        "",
        "namespace",
        "{",
        "",
        "// Indexed by rule value: the enum reserves regions by pinning some rules to a byte",
        "// boundary, so it has gaps, and those stay null.",
        "const std::array<const char*, qr_MAX> qr_names = []{",
        "\tstd::array<const char*, qr_MAX> names{};",
    ]
    lines += [f'\tnames[{name}] = "{name}";' for name in names]
    lines += [
        "\treturn names;",
        "}();",
        "",
        "}",
        "",
        "// qr_name lives here rather than in qrs.cpp so that targets which compile qrs.cpp",
        "// without linking `core` (zscript) do not need this generated file.",
        "const char* qr_name(int index)",
        "{",
        "\tif (unsigned(index) >= qr_MAX)",
        "\t\treturn nullptr;",
        "",
        "\treturn qr_names[index];",
        "}",
        "",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
