//NEWCOMBO STRUCT


#define COMBODTILE		0x12B7	//word
#define COMBODFLIP		0x12B8	//char
#define COMBODWALK		0x12B9	//char
#define COMBODTYPE		0x12BA	//char
#define COMBODCSET		0x12BC	//C
#define COMBODFOO		0x12BD	//W
#define COMBODFRAMES		0x12BE	//C
#define COMBODNEXTD		0x12BF	//W
#define COMBODNEXTC		0x12C0	//C
#define COMBODFLAG		0x12C1	//C
#define COMBODSKIPANIM		0x12C2	//C
#define COMBODNEXTTIMER		0x12C3	//W
#define COMBODAKIMANIMY		0x12C4	//C
#define COMBODANIMFLAGS		0x12C5	//C
#define COMBODEXPANSION		0x12C6	//C , 6 INDICES
#define COMBODATTRIBUTES 	0x12C7	//LONG, 4 INDICES, INDIVIDUAL VALUES
#define COMBODUSRFLAGS		0x12C8	//LONG
#define COMBODTRIGGERFLAGS	0x12C9	//LONG 3 INDICES AS FLAGSETS
#define COMBODTRIGGERLEVEL	0x12CA	//LONG

//COMBOCLASS STRUCT
#define COMBODNAME		0x12CB	//CHAR[64], STRING
#define COMBODBLOCKNPC		0x12CC	//C
#define COMBODBLOCKHOLE		0x12CD	//C
#define COMBODBLOCKTRIG		0x12CE	//C
#define COMBODBLOCKWEAPON	0x12CF	//C, 32 INDICES
#define COMBODCONVXSPEED	0x12D0	//SHORT
#define COMBODCONVYSPEED	0x12D1	//SHORT
#define COMBODSPAWNNPC		0x12D2	//W
#define COMBODSPAWNNPCWHEN	0x12D3	//C
#define COMBODSPAWNNPCCHANGE	0x12D4	//LONG
#define COMBODDIRCHANGETYPE	0x12D5	//C
#define COMBODDISTANCECHANGETILES	0x12D6	//LONG
#define COMBODDIVEITEM		0x12D7	//SHORT
#define COMBODDOCK		0x12D8	//C
#define COMBODFAIRY		0x12D9	//C
#define COMBODFFATTRCHANGE	0x12DA	//C
#define COMBODFOORDECOTILE	0x12DB	//LONG
#define COMBODFOORDECOTYPE	0x12DC	//C
#define COMBODHOOKSHOTPOINT	0x12DD	//C
#define COMBODLADDERPASS	0x12DE	//C
#define COMBODLOCKBLOCK		0x12DF	//C
#define COMBODLOCKBLOCKCHANGE	0x12E0	//LONG
#define COMBODMAGICMIRROR	0x12E1	//C
#define COMBODMODHPAMOUNT	0x12E2	//SHORT
#define COMBODMODHPDELAY	0x12E3	//C
#define COMBODMODHPTYPE		0x12E4	//C
#define COMBODNMODMPAMOUNT	0x12E5	//SHORT
#define COMBODMODMPDELAY	0x12E6	//C
#define COMBODMODMPTYPE		0x12E7	//C
#define COMBODNOPUSHBLOCK	0x12E8	//C
#define COMBODOVERHEAD		0x12E9	//C
#define COMBODPLACENPC		0x12EA	//C
#define COMBODPUSHDIR		0x12EB	//C
#define COMBODPUSHWEIGHT	0x12EC	//C
#define COMBODPUSHHEAVY		0x12ED	//C
#define COMBODPUSHED		0x12EE	//C
#define COMBODRAFT		0x12EF	//C
#define COMBODRESETROOM		0x12F0	//C
#define COMBODSAVEPOINTTYPE	0x12F1	//C
#define COMBODSCREENFREEZETYPE	0x12F2	//C
#define COMBODSECRETCOMBO	0x12F3	//C
#define COMBODSINGULAR		0x12F4	//C
#define COMBODSLOWWALK		0x12F5	//C
#define COMBODSTATUETYPE	0x12F6	//C
#define COMBODSTEPTYPE		0x12F7	//C
#define COMBODSTEPCHANGEINTO	0x12F8	//LONG
#define COMBODSTRIKEWEAPONS	0x12F9	//BYTE, 32 INDICES. 
#define COMBODSTRIKEREMNANTS	0x12FA	//LONG
#define COMBODSTRIKEREMNANTSTYPE	0x12FB	//C
#define COMBODSTRIKECHANGE	0x12FC	//LONG
#define COMBODSTRIKEITEM	0x12FD	//SHORT
#define COMBODTOUCHITEM		0x12FE	//SHORT
#define COMBODTOUCHSTAIRS	0x12FF	//C
#define COMBODTRIGGERTYPE	0x1300	//C
#define COMBODTRIGGERSENS	0x1301	//C
#define COMBODWARPTYPE		0x1302	//C
#define COMBODWARPSENS		0x1303	//C
#define COMBODWARPDIRECT	0x1304	//C
#define COMBODWARPLOCATION	0x1305	//C
#define COMBODWATER		0x1306	//C
#define COMBODWHISTLE		0x1307	//C
#define COMBODWINGAME		0x1308	//C
#define COMBODBLOCKWPNLEVEL	0x1309	//C

0x130A

//bytecode

//NEWCOMBO STRUCT

#define COMBODTILE		882	//word
#define COMBODFLIP		883	//char
#define COMBODWALK		884	//char
#define COMBODTYPE		885	//char
#define COMBODCSET		886	//C
#define COMBODFOO		887	//W
#define COMBODFRAMES		888	//C
#define COMBODNEXTD		889	//W
#define COMBODNEXTC		890	//C
#define COMBODFLAG		891	//C
#define COMBODSKIPANIM		893	//C
#define COMBODNEXTTIMER		893	//W
#define COMBODAKIMANIMY		894	//C
#define COMBODANIMFLAGS		895	//C
#define COMBODEXPANSION		896	//C , 6 INDICES
#define COMBODATTRIBUTES 	897	//LONG, 4 INDICES, INDIVIDUAL VALUES
#define COMBODUSRFLAGS		898	//LONG
#define COMBODTRIGGERFLAGS	899	//LONG 3 INDICES AS FLAGSETS
#define COMBODTRIGGERLEVEL	900	//LONG

//COMBOCLASS STRUCT
#define COMBODNAME		901	//CHAR[64], STRING
#define COMBODBLOCKNPC		902	//C
#define COMBODBLOCKHOLE		903	//C
#define COMBODBLOCKTRIG		904	//C
#define COMBODBLOCKWEAPON	905	//C, 32 INDICES
#define COMBODCONVXSPEED	906	//SHORT
#define COMBODCONVYSPEED	907	//SHORT
#define COMBODSPAWNNPC		908	//W
#define COMBODSPAWNNPCWHEN	909	//C
#define COMBODSPAWNNPCCHANGE	910	//LONG
#define COMBODDIRCHANGETYPE	911	//C
#define COMBODDISTANCECHANGETILES	912	//LONG
#define COMBODDIVEITEM		913	//SHORT
#define COMBODDOCK		914	//C
#define COMBODFAIRY		915	//C
#define COMBODFFATTRCHANGE	916	//C
#define COMBODFOORDECOTILE	917	//LONG
#define COMBODFOORDECOTYPE	918	//C
#define COMBODHOOKSHOTPOINT	919	//C
#define COMBODLADDERPASS	920	//C
#define COMBODLOCKBLOCK		921	//C
#define COMBODLOCKBLOCKCHANGE	922	//LONG
#define COMBODMAGICMIRROR	923	//C
#define COMBODMODHPAMOUNT	924	//SHORT
#define COMBODMODHPDELAY	925	//C
#define COMBODMODHPTYPE		926	//C
#define COMBODNMODMPAMOUNT	927	//SHORT
#define COMBODMODMPDELAY	928	//C
#define COMBODMODMPTYPE		929	//C
#define COMBODNOPUSHBLOCK	930	//C
#define COMBODOVERHEAD		931	//C
#define COMBODPLACENPC		932	//C
#define COMBODPUSHDIR		933	//C
#define COMBODPUSHWEIGHT	934	//C
#define COMBODPUSHHEAVY		935	//C
#define COMBODPUSHED		936	//C
#define COMBODRAFT		937	//C
#define COMBODRESETROOM		938	//C
#define COMBODSAVEPOINTTYPE	939	//C
#define COMBODSCREENFREEZETYPE	940	//C
#define COMBODSECRETCOMBO	941	//C
#define COMBODSINGULAR		942	//C
#define COMBODSLOWWALK		943	//C
#define COMBODSTATUETYPE	944	//C
#define COMBODSTEPTYPE		945	//C
#define COMBODSTEPCHANGEINTO	946	//LONG
#define COMBODSTRIKEWEAPONS	947	//BYTE, 32 INDICES. 
#define COMBODSTRIKEREMNANTS	948	//LONG
#define COMBODSTRIKEREMNANTSTYPE 949	//C
#define COMBODSTRIKECHANGE	950	//LONG
#define COMBODSTRIKEITEM	951	//SHORT
#define COMBODTOUCHITEM		952	//SHORT
#define COMBODTOUCHSTAIRS	953	//C
#define COMBODTRIGGERTYPE	954	//C
#define COMBODTRIGGERSENS	955	//C
#define COMBODWARPTYPE		956	//C
#define COMBODWARPSENS		957	//C
#define COMBODWARPDIRECT	958	//C
#define COMBODWARPLOCATION	959	//C
#define COMBODWATER		960	//C
#define COMBODWHISTLE		961	//C
#define COMBODWINGAME		962	//C
#define COMBODBLOCKWPNLEVEL	963	//C

964
