    { "getValid",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAVALID,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getGuy",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAGUY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getString",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASTRING,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getRoomType",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAROOM,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getItem",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAITEM,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getHasItem",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAHASITEM,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getTileWarpType[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPTYPE,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getTileWarpOverlayFlags",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPOVFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getDoorComboSet",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATADOORCOMBOSET,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getWarpReturnX[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPRETX,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getWarpReturnY[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPRETY,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getWarpReturnC",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPRETURNC,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getStairsX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASTAIRX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getStairsY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASTAIRY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getItemX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAITEMX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getItemY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAITEMY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getCSet",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATACOLOUR,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getEnemyFlags",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENEMYFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getDoor[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATADOOR,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getTileWarpDMap[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPDMAP,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getTileWarpScreen[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPSCREEN,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getExitDir",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAEXITDIR,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getEnemy[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENEMY,           10,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getPattern",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAPATTERN,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSideWarpType[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPTYPE,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSideWarpOverlayFlags",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPOVFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getWarpArrivalX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPARRIVALX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getWarpArrivalY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPARRIVALY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getMazePath[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAPATH,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSideWarpScreen[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPSC,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSideWarpDMap[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPDMAP,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSideWarpIndex",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPINDEX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getUndercombo",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAUNDERCOMBO,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getUnderCSet",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAUNDERCSET,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getCatchall",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATACATCHALL,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getCSensitive",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATACSENSITIVE,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getNoReset",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANORESET,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getNoCarry",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANOCARRY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getLayerMap[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALAYERMAP,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getLayerScreen[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALAYERSCREEN,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getLayerOpacity[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALAYEROPACITY,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getTimedWarpTimer",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATIMEDWARPTICS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getNextMap",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANEXTMAP,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getNextScreen",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANEXTSCREEN,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSecretCombo[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETCOMBO,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSecretCSet[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETCSET,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSecretFlags[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETFLAG,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getViewX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAVIEWX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getViewY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAVIEWY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getWidth",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCREENWIDTH,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getHeight",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCREENHEIGHT,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getEntryX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENTRYX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getEntryY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENTRYY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getNumFFCs",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANUMFF,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCData[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFDATA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCCSet[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFCSET,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCDelay[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFDELAY,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCX[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFX,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCY[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFY,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCVx[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFXDELTA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCVy[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFYDELTA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCAx[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFXDELTA2,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCAy[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFYDELTA2,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCFlags[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFFLAGS,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
     
    { "getFFCEffectWidth[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFEFFECTWIDTH,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCEffectHeight[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFEFFECTHEIGHT,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCTileWidth[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFWIDTH,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCTileHeight[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFHEIGHT,           32,      {  ScriptParser::TYPE_MAPDATA,        ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
 
    { "getFFCLink[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFLINK,           32,      {  ScriptParser::TYPE_MAPDATA,         ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCScript[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFSCRIPT,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFFCRunning[]",              ScriptParser::TYPE_BOOL,         GETTER,       MAPDATAFFINITIALISED,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getScriptEntry",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCRIPTENTRY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getScriptOccupancy",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCRIPTOCCUPANCY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getExitScript",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCRIPTEXIT,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getOceanSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAOCEANSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getBossSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATABOSSSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getSecretSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getItemSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAHOLDUPSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getMIDI",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCREENMIDI,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getLensLayer",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALENSLAYER,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "getFlags[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFLAGS,           11,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    //array of 11
    { "getD[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAINTID,           10,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
     //array of 10 MAPDATAMISCD
    

