    { "setValid",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAVALID,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setGuy",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAGUY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setString",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASTRING,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setRoomType",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAROOM,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setItem",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAITEM,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setHasItem",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAHASITEM,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setTileWarpType[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATATILEWARPTYPE,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setTileWarpOverlayFlags",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATATILEWARPOVFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setDoorComboSet",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATADOORCOMBOSET,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setWarpReturnX[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAWARPRETX,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setWarpReturnY[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAWARPRETY,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setWarpReturnC",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAWARPRETURNC,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setStairsX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASTAIRX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setStairsY",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASTAIRY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setItemX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAITEMX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setItemY",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAITEMY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setCSet",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATACOLOUR,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setEnemyFlags",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAENEMYFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setDoor[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATADOOR,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setTileWarpDMap[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATATILEWARPDMAP,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setTileWarpScreen[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATATILEWARPSCREEN,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setExitDir",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAEXITDIR,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setEnemy",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAENEMY,           10,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setPattern",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAPATTERN,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSideWarpType[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASIDEWARPTYPE,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSideWarpOverlayFlags",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASIDEWARPOVFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setWarpArrivalX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAWARPARRIVALX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setWarpArrivalY",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAWARPARRIVALY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setMazePath[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAPATH,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSideWarpScreen[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASIDEWARPSC,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSideWarpDMap[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASIDEWARPDMAP,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSideWarpIndex",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASIDEWARPINDEX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setUndercombo",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAUNDERCOMBO,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setUnderCSet",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAUNDERCSET,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setCatchall",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATACATCHALL,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setCSensitive",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATACSENSITIVE,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setNoReset",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATANORESET,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setNoCarry",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATANOCARRY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setLayerMap[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATALAYERMAP,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setLayerScreen[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATALAYERSCREEN,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setLayerOpacity[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATALAYEROPACITY,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setTimedWarpTimer",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATATIMEDWARPTICS,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setNextMap",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATANEXTMAP,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setNextScreen",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATANEXTSCREEN,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSecretCombo[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASECRETCOMBO,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSecretCSet[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASECRETCSET,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSecretFlags[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASECRETFLAG,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setViewX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAVIEWX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setViewY",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAVIEWY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setWidth",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASCREENWIDTH,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setHeight",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASCREENHEIGHT,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setEntryX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAENTRYX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setEntryY",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAENTRYY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setNumFFCs",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATANUMFF,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCData[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFDATA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCCSet[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFCSET,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCDelay[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFDELAY,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCX[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFX,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCY[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFY,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCVx[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFXDELTA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCVy[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFYDELTA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCAx[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFXDELTA2,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCAy[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFYDELTA2,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCFlags[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFFLAGS,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
     
    { "setFFCEffectWidth[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFEFFECTWIDTH,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCEffectHeight[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFEFFECTHEIGHT,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCTileWidth[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFWIDTH,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCTileHeight[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFHEIGHT,           32,      {  ScriptParser::TYPE_MAPDATA,        ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
 
    { "setFFCLink[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFLINK,           32,      {  ScriptParser::TYPE_MAPDATA,         ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCScript[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFSCRIPT,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFFCRunning[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFFINITIALISED,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                ScriptParser::TYPE_BOOL,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setScriptEntry",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASCRIPTENTRY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setScriptOccupancy",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASCRIPTOCCUPANCY,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setExitScript",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASCRIPTEXIT,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setOceanSFX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAOCEANSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setBossSFX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATABOSSSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setSecretSFX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASECRETSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setItemSFX",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAHOLDUPSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setMIDI",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATASCREENMIDI,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setLensLayer",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATALENSLAYER,           1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "setFlags[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAFLAGS,           11,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    //array of 11
    { "setD[]",              ScriptParser::TYPE_VOID,         SETTER,       MAPDATAINTID,           10,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
     //array of 10 MAPDATAMISCD
    