    { "Valid",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAVALID,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Guy",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAGUY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "String",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASTRING,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "RoomType",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAROOM,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Item",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAITEM,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "HasItem",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAHASITEM,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "TileWarpType[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPTYPE,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "TileWarpOverlayFlags",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPOVFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "DoorComboSet",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATADOORCOMBOSET,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "WarpReturnX[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPRETX,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "WarpReturnY[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPRETY,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "WarpReturnC",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPRETURNC,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "StairsX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASTAIRX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "StairsY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASTAIRY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ItemX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAITEMX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ItemY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAITEMY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "CSet",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATACOLOUR,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "EnemyFlags",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENEMYFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Door[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATADOOR,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "TileWarpDMap[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPDMAP,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "TileWarpScreen[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATILEWARPSCREEN,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ExitDir",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAEXITDIR,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Enemy[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENEMY,           10,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Pattern",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAPATTERN,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SideWarpType[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPTYPE,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SideWarpOverlayFlags",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPOVFLAGS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "WarpArrivalX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPARRIVALX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "WarpArrivalY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAWARPARRIVALY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "MazePath[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAPATH,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SideWarpScreen[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPSC,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SideWarpDMap[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPDMAP,           4,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SideWarpIndex",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASIDEWARPINDEX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Undercombo",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAUNDERCOMBO,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "UnderCSet",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAUNDERCSET,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Catchall",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATACATCHALL,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "CSensitive",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATACSENSITIVE,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "NoReset",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANORESET,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "NoCarry",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANOCARRY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "LayerMap[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALAYERMAP,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "LayerScreen[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALAYERSCREEN,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "LayerOpacity[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALAYEROPACITY,           6,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "TimedWarpTimer",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATATIMEDWARPTICS,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "NextMap",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANEXTMAP,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "NextScreen",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANEXTSCREEN,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SecretCombo[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETCOMBO,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SecretCSet[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETCSET,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SecretFlags[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETFLAG,           128,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ViewX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAVIEWX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ViewY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAVIEWY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Width",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCREENWIDTH,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Height",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCREENHEIGHT,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "EntryX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENTRYX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "EntryY",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAENTRYY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "NumFFCs",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATANUMFF,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCData[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFDATA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCCSet[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFCSET,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCDelay[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFDELAY,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCX[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFX,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCY[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFY,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCVx[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFXDELTA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCVy[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFYDELTA,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCAx[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFXDELTA2,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCAy[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFYDELTA2,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCFlags[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFFLAGS,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
     
    { "FFCEffectWidth[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFEFFECTWIDTH,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCEffectHeight[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFEFFECTHEIGHT,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCTileWidth[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFWIDTH,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCTileHeight[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFHEIGHT,           32,      {  ScriptParser::TYPE_MAPDATA,        ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
 
    { "FFCLink[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFLINK,           32,      {  ScriptParser::TYPE_MAPDATA,         ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCScript[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFFSCRIPT,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "FFCRunning[]",              ScriptParser::TYPE_BOOL,         GETTER,       MAPDATAFFINITIALISED,           32,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                                -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ScriptEntry",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCRIPTENTRY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ScriptOccupancy",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCRIPTOCCUPANCY,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ExitScript",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCRIPTEXIT,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "OceanSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAOCEANSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "BossSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATABOSSSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "SecretSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASECRETSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "ItemSFX",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAHOLDUPSFX,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "MIDI",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATASCREENMIDI,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "LensLayer",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATALENSLAYER,           1,      {  ScriptParser::TYPE_MAPDATA,          -1,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "Flags[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAFLAGS,           11,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    //array of 11
    { "D[]",              ScriptParser::TYPE_FLOAT,         GETTER,       MAPDATAINTID,           10,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,                               -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
     //array of 10 MAPDATAMISCD
    
   
 //Functions

    { "GetFFCInitD",              ScriptParser::TYPE_FLOAT,          FUNCTION,     0,                    1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,        ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    { "SetFFCInitD",              ScriptParser::TYPE_VOID,          FUNCTION,     0,                    1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,        ScriptParser::TYPE_FLOAT,                           ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
    { "GetFFCInitA",              ScriptParser::TYPE_FLOAT,          FUNCTION,     0,                    1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,        ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    { "SetFFCInitA",              ScriptParser::TYPE_FLOAT,          FUNCTION,     0,                    1,      {  ScriptParser::TYPE_MAPDATA,          ScriptParser::TYPE_FLOAT,        ScriptParser::TYPE_FLOAT,                           ScriptParser::TYPE_FLOAT,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1,                           -1                           } },
    
	

	//inita	//INT32, 32 OF THESE, EACH WITH 2


