//Graphics->Colors[]
#define GFXCOLOURS				//CHAR[]

//drop an item: CreateDrop(int x, int y, int z)
//item CreateItemDrop(int x, int y, int z) 
//int CreateItemDrop() return -1 on no drop. 
#define CREATEDROP

//item_drop_sets[MAXITEMDROPSETS];
#define DROPDATANAME				//CHAR[64]
#define DROPDATAITEM				//W, 10 INDICES
#define DROPDATACHANCE				//W, 11 INDICES
#define QUESTTRIFORCE				//C, 8 INDICES
#define QUESTENDSTRING				//W, STRING EDITOR VALUE
#define QUESTICON				//W, 4 INDICES
#define WARPRINGNAME 				//CHAR[32]
#define WARPRINGDMAP				//W, 9 INDICES
#define WARPRINGSCREEN				//W, 9 INDICES
#define WARPRINGSIZE				//C
#define CHEATFLAGS				//W
#define CHEATCODELV1				//CHAR[41], LET'S USE A DIRECT STRING?
#define CHEATCODELV2				//CHAR[41], LET'S USE A DIRECT STRING?
#define CHEATCODELV3				//CHAR[41], LET'S USE A DIRECT STRING?
#define CHEATCODELV4				//CHAR[41], LET'S USE A DIRECT STRING?
	
#define PALCYCLEFIRST				//C
#define PALCYCLECOUNT				//C
#define PALCYCLESPEED				//C

#define ZCTUNETITLE				//CHAR[36]
#define ZCTUNESTART				//LONG
#define ZCTUNELOOPSTART				//LONG
#define ZCTUNELOOPEND				//LONG
#define ZCTUNELOOP				//SHORT
#define ZCTUNEVOLUME				//SHORT
#define ZCTUNEFLAGS				//C
#define ZCTUNEFORMAT				//C --READ ONLY IS PROBABLY BEST

#define GAMEQUESTVERSION			//CHAR[9]
#define GAMEQUESTTITLE				//CHAR[65]

#define ZCOLOURTEXT				//C
#define ZCOLOURCAPTION				//C
#define ZCOLOUROVERWORLDBG			//C
#define ZCOLOURDUNGEONBG			//C
#define ZCOLOURDUNGEONFG			//C
#define ZCOLOURCAVEFG				//C
#define ZCOLOURBSDARK				//C
#define ZCOLOURBSGOAL				//C
#define ZCOLOURCOMPASSLIGHT			//C
#define ZCOLOURCOMPASSDARK			//C
#define ZCOLOURSUBSCREENBG			//C
#define ZCOLOURSUBSCREENSHADOW			//C
#define ZCOLOURTRIFRAME				//C
#define ZCOLOURBIGMAPBG				//C
#define ZCOLOURBIGMAPFG				//C
#define ZCOLOURLINKDOT				//C
#define ZCOLOURTRIFORCECSET			//C
#define ZCOLOURTRIFRAMECSET			//C
#define ZCOLOUROVERWORLDMAPCSET			//C
#define ZCOLOURDUNGEONMAPCSET			//C
#define ZCOLOURBLUEFRAMECSET			//C
#define ZCOLOURTRIFORCETILE			//W
#define ZCOLOURTRIFRAMETILE			//W
#define ZCOLOUROVERWORLDMAPTILE			//W
#define ZCOLOURDUNGEONMAPTILE			//W
#define ZCOLOURBLUEFRAMETILE			//W
#define ZCOLOURHCPIECETILE			//W
#define ZCOLOURHCPIECECSET			//C
#define ZCOLOURMSGTEXT				//C
#define ZCOLOURFOO				//C, 6 INDICES
#define ZCOLOURFOO2				//C, 256 INDICES