//Graphics->Colors[]
{"GFXCOLOURS", GFXCOLOURS, 0, 0 },

//drops
{"DROPDATANAME", DROPDATANAME, 0, 0 },
{"DROPDATAITEM", DROPDATAITEM, 0, 0 },
{"DROPDATACHANCE", DROPDATACHANCE, 0, 0 },

//miscqdata
{"QUESTTRIFORCE", QUESTTRIFORCE, 0, 0 },
{"QUESTENDSTRING", QUESTENDSTRING, 0, 0 },
{"QUESTICON", QUESTICON, 0, 0 },

//warpring
{"WARPRINGNAME", WARPRINGNAME, 0, 0 },
{"WARPRINGDMAP", WARPRINGDMAP, 0, 0 },
{"WARPRINGSCREEN", WARPRINGSCREEN, 0, 0 },
{"WARPRINGSIZE", WARPRINGSIZE, 0, 0 },

//cheat
{"CHEATFLAGS", CHEATFLAGS, 0, 0 },
{"CHEATCODELV1", CHEATCODELV1, 0, 0 },
{"CHEATCODELV2", CHEATCODELV2, 0, 0 },
{"CHEATCODELV3", CHEATCODELV3, 0, 0 },
{"CHEATCODELV4", CHEATCODELV4, 0, 0 },

{"PALCYCLEFIRST", PALCYCLEFIRST, 0, 0 },
{"PALCYCLECOUNT", PALCYCLECOUNT, 0, 0 },
{"PALCYCLESPEED", PALCYCLESPEED, 0, 0 },

{"ZCTUNETITLE", ZCTUNETITLE, 0, 0 },
{"ZCTUNESTART", ZCTUNESTART, 0, 0 },
{"ZCTUNELOOPSTART", ZCTUNELOOPSTART, 0, 0 },
{"ZCTUNELOOPEND", ZCTUNELOOPEND, 0, 0 },
{"ZCTUNELOOP", ZCTUNELOOP, 0, 0 },
{"ZCTUNEVOLUME", ZCTUNEVOLUME, 0, 0 },
{"ZCTUNEFLAGS", ZCTUNEFLAGS, 0, 0 },
{"ZCTUNEFORMAT", ZCTUNEFORMAT, 0, 0 },

{"GAMEQUESTVERSION", COMBODTILE, 0, 0 },
{"GAMEQUESTTITLE", COMBODTILE, 0, 0 },
///quest number?

{"ZCOLOURTEXT", ZCOLOURTEXT, 0, 0 },
{"ZCOLOURCAPTION", ZCOLOURCAPTION, 0, 0 },
{"ZCOLOUROVERWORLDBG", ZCOLOUROVERWORLDBG, 0, 0 },
{"ZCOLOURDUNGEONBG", ZCOLOURDUNGEONBG, 0, 0 },
{"ZCOLOURDUNGEONFG", ZCOLOURDUNGEONFG, 0, 0 },
{"ZCOLOURCAVEFG", ZCOLOURCAVEFG, 0, 0 },
{"ZCOLOURBSDARK", ZCOLOURBSDARK, 0, 0 },
{"ZCOLOURBSGOAL", ZCOLOURBSGOAL, 0, 0 },
{"ZCOLOURCOMPASSLIGHT", ZCOLOURCOMPASSLIGHT, 0, 0 },
{"ZCOLOURCOMPASSDARK", ZCOLOURCOMPASSDARK, 0, 0 },
{"ZCOLOURSUBSCREENBG", ZCOLOURSUBSCREENBG, 0, 0 },
{"ZCOLOURSUBSCREENSHADOW", ZCOLOURSUBSCREENSHADOW, 0, 0 },
{"ZCOLOURTRIFRAME", ZCOLOURTRIFRAME, 0, 0 },
{"ZCOLOURBIGMAPBG", ZCOLOURBIGMAPBG, 0, 0 },
{"ZCOLOURBIGMAPFG", ZCOLOURBIGMAPFG, 0, 0 },
{"ZCOLOURLINKDOT", ZCOLOURLINKDOT, 0, 0 },
{"ZCOLOURTRIFORCECSET", ZCOLOURTRIFORCECSET, 0, 0 },
{"ZCOLOURTRIFRAMECSET", ZCOLOURTRIFRAMECSET, 0, 0 },
{"ZCOLOUROVERWORLDMAPCSET", ZCOLOUROVERWORLDMAPCSET, 0, 0 },
{"ZCOLOURDUNGEONMAPCSET", ZCOLOURDUNGEONMAPCSET, 0, 0 },
{"ZCOLOURBLUEFRAMECSET", ZCOLOURBLUEFRAMECSET, 0, 0 },
{"ZCOLOURTRIFORCETILE", ZCOLOURTRIFORCETILE, 0, 0 },
{"ZCOLOURTRIFRAMETILE", ZCOLOURTRIFRAMETILE, 0, 0 },
{"ZCOLOUROVERWORLDMAPTILE", ZCOLOUROVERWORLDMAPTILE, 0, 0 },
{"ZCOLOURDUNGEONMAPTILE", ZCOLOURDUNGEONMAPTILE, 0, 0 },
{"ZCOLOURBLUEFRAMETILE", ZCOLOURBLUEFRAMETILE, 0, 0 },
{"ZCOLOURHCPIECETILE", ZCOLOURHCPIECETILE, 0, 0 },
{"ZCOLOURHCPIECECSET", ZCOLOURHCPIECECSET, 0, 0 },
{"ZCOLOURMSGTEXT", ZCOLOURMSGTEXT, 0, 0 },
{"ZCOLOURFOO", ZCOLOURFOO, 0, 0 },
{"ZCOLOURFOO2", ZCOLOURFOO2, 0, 0 },
