//newcombo struct
case DROPDATANAME: return "DROPDATANAME";
case DROPDATAITEM: return "DROPDATAITEM";
case DROPDATACHANCE: return "DROPDATACHANCE";

//miscQData
case QUESTTRIFORCE: return "QUESTTRIFORCE";
case QUESTENDSTRING: return "QUESTENDSTRING";
case QUESTICON: return "QUESTICON";
//warpring
case WARPRINGNAME: return "WARPRINGNAME";
case WARPRINGDMAP: return "WARPRINGDMAP";
case WARPRINGSCREEN: return "WARPRINGSCREEN";
case WARPRINGSIZE: return "WARPRINGSIZE";

//zcheats
case CHEATFLAGS: return "CHEATFLAGS";
case CHEATCODELV1: return "CHEATCODELV1";
case CHEATCODELV2: return "CHEATCODELV2";
case CHEATCODELV3: return "CHEATCODELV3";
case CHEATCODELV4: return "CHEATCODELV4";

case PALCYCLEFIRST: return "PALCYCLEFIRST";
case PALCYCLECOUNT: return "PALCYCLECOUNT";
case PALCYCLESPEED: return "PALCYCLESPEED";

case ZCTUNETITLE: return "ZCTUNETITLE";
case ZCTUNESTART: return "ZCTUNESTART";
case ZCTUNELOOPSTART: return "ZCTUNELOOPSTART";
case ZCTUNELOOPEND: return "ZCTUNELOOPEND";
case ZCTUNELOOP: return "ZCTUNELOOP";
case ZCTUNEVOLUME: return "ZCTUNEVOLUME";
case ZCTUNEFLAGS: return "ZCTUNEFLAGS";
case ZCTUNEFORMAT: return "ZCTUNEFORMAT";

case GAMEQUESTVERSION: return "GAMEQUESTVERSION";
case GAMEQUESTTITLE: return "GAMEQUESTTITLE";
//quest number?

//zcolours
case ZCOLOURTEXT: return "ZCOLOURTEXT";
case ZCOLOURCAPTION: return "ZCOLOURCAPTION";
case ZCOLOUROVERWORLDBG: return "ZCOLOUROVERWORLDBG";
case ZCOLOURDUNGEONBG: return "ZCOLOURDUNGEONBG";
case ZCOLOURDUNGEONFG: return "ZCOLOURDUNGEONFG";
case ZCOLOURCAVEFG: return "ZCOLOURCAVEFG";
case ZCOLOURBSDARK: return "ZCOLOURBSDARK";
case ZCOLOURBSGOAL: return "ZCOLOURBSGOAL";
case ZCOLOURCOMPASSLIGHT: return "ZCOLOURCOMPASSLIGHT";
case ZCOLOURCOMPASSDARK: return "ZCOLOURCOMPASSDARK";
case ZCOLOURSUBSCREENBG: return "ZCOLOURSUBSCREENBG";
case ZCOLOURSUBSCREENSHADOW: return "ZCOLOURSUBSCREENSHADOW";
case ZCOLOURTRIFRAME: return "ZCOLOURTRIFRAME";
case ZCOLOURBIGMAPBG: return "ZCOLOURBIGMAPBG";
case ZCOLOURBIGMAPFG: return "ZCOLOURBIGMAPFG";
case ZCOLOURLINKDOT: return "ZCOLOURLINKDOT";
case ZCOLOURTRIFORCECSET: return "ZCOLOURTRIFORCECSET";
case ZCOLOURTRIFRAMECSET: return "ZCOLOURTRIFRAMECSET";
case ZCOLOUROVERWORLDMAPCSET: return "ZCOLOUROVERWORLDMAPCSET";
case ZCOLOURDUNGEONMAPCSET: return "ZCOLOURDUNGEONMAPCSET";
case ZCOLOURBLUEFRAMECSET: return "ZCOLOURBLUEFRAMECSET";
case ZCOLOURTRIFORCETILE: return "ZCOLOURTRIFORCETILE";
case ZCOLOURTRIFRAMETILE: return "ZCOLOURTRIFRAMETILE";
case ZCOLOUROVERWORLDMAPTILE: return "ZCOLOUROVERWORLDMAPTILE";
case ZCOLOURDUNGEONMAPTILE: return "ZCOLOURDUNGEONMAPTILE";
case ZCOLOURBLUEFRAMETILE: return "ZCOLOURBLUEFRAMETILE";
case ZCOLOURHCPIECETILE: return "ZCOLOURHCPIECETILE";
case ZCOLOURHCPIECECSET: return "ZCOLOURHCPIECECSET";
case ZCOLOURMSGTEXT: return "ZCOLOURMSGTEXT";
case ZCOLOURFOO: return "ZCOLOURFOO";
case ZCOLOURFOO2: return "ZCOLOURFOO2";
