//item_drop_sets[MAXITEMDROPSETS];
DROPDATANAME	//CHAR[64]
DROPDATAITEM	//W, 10 INDICES
DROPDATACHANCE	//W, 11 INDICES

int ref = ri->dropsref; 
int indx = ri->d[0] / 10000; 
if ( indx < 0 || indx > 10 ) 
{ 
	Z_scripterrlog("Invalid Array Index passed to shopdata->%s: %d\n", indx, "HasItem"); 
} 
ret = ((int)item_drop_sets[ref].chance[indx] * 10000;
ret = ((int)item_drop_sets[ref].item[indx] * 10000;


//miscQdata
QUESTTRIFORCE		//C, 8 INDICES
QUESTENDSTRING		//W, STRING EDITOR VALUE
QUESTICON		//W, 4 INDICES

//warpring
WARPRINGNAME 	//CHAR[32]
WARPRINGDMAP	//W, 9 INDICES
WARPRINGSCREEN	//W, 9 INDICES
WARPRINGSIZE	//C

//ZCHEATS
CHEATFLAGS	//W
CHEATCODELV1	//CHAR[41], LET'S USE A DIRECT STRING?
CHEATCODELV2	//CHAR[41], LET'S USE A DIRECT STRING?
CHEATCODELV3	//CHAR[41], LET'S USE A DIRECT STRING?
CHEATCODELV4	//CHAR[41], LET'S USE A DIRECT STRING?

int ref = ri->shopsref; 

ret = ((int)(misc->cycles[ref].member[indx]) * 10000);
misc->cycles[ref].members[indx] = (byte)(vbound((value/10000), 0, 255)); 
		
	
PALCYCLEFIRST	//C
PALCYCLECOUNT	//C
PALCYCLESPEED	//C


int ref = ri->shopsref; 
ret = ((int)(misc->cycles[ref][0]) * 10000); //first
ret = ((int)(misc->cycles[ref][1]) * 10000); //count
ret = ((int)(misc->cycles[ref][2]) * 10000); //speed
palcycle cycles[256][3];

//miscQdata
ret = ((int)(misc->shop[ref].item[indx]) * 10000);
misc->shop[ref].item[indx] = (byte)(vbound((value/10000), 0, 255)); 
	
	

ZCTUNETITLE	//CHAR[36]
ZCTUNESTART	//LONG
ZCTUNELOOPSTART	//LONG
ZCTUNELOOPEND	//LONG
ZCTUNELOOP	//SHORT
ZCTUNEVOLUME	//SHORT
ZCTUNEFLAGS	//C
ZCTUNEFORMAT	//C --READ ONLY IS PROBABLY BEST

GAMEQUESTVERSION	//CHAR[9]
GAMEQUESTTITLE		//CHAR[65]

//zcolors --these should all be palette indices, not raw RGB data
ZCOLOURTEXT	//C
ZCOLOURCAPTION	//C
ZCOLOUROVERWORLDBG	//C
ZCOLOURDUNGEONBG	//C
ZCOLOURDUNGEONFG	//C
ZCOLOURCAVEFG		//C
ZCOLOURBSDARK		//C
ZCOLOURBSGOAL		//C
ZCOLOURCOMPASSLIGHT	//C
ZCOLOURCOMPASSDARK	//C
ZCOLOURSUBSCREENBG	//C
ZCOLOURSUBSCREENSHADOW	//C
ZCOLOURTRIFRAME		//C
ZCOLOURBIGMAPBG		//C
ZCOLOURBIGMAPFG		//C
ZCOLOURLINKDOT		//C
ZCOLOURTRIFORCECSET	//C
ZCOLOURTRIFRAMECSET	//C
ZCOLOUROVERWORLDMAPCSET	//C
ZCOLOURDUNGEONMAPCSET	//C
ZCOLOURBLUEFRAMECSET	//C
ZCOLOURTRIFORCETILE	//W
ZCOLOURTRIFRAMETILE	//W
ZCOLOUROVERWORLDMAPTILE	//W
ZCOLOURDUNGEONMAPTILE	//W
ZCOLOURBLUEFRAMETILE	//W
ZCOLOURHCPIECETILE	//W
ZCOLOURHCPIECECSET	//C
ZCOLOURMSGTEXT		//C
ZCOLOURFOO		//C, 6 INDICES
ZCOLOURFOO2		//C, 256 INDICES