//item_drop_sets[MAXITEMDROPSETS];
case DROPDATANAME:				//CHAR[64]
case DROPDATAITEM:				//W, 10 INDICES
case DROPDATACHANCE:				//W, 11 INDICES
case QUESTTRIFORCE:				//C, 8 INDICES
case QUESTENDSTRING:				//W, STRING EDITOR VALUE
case QUESTICON:				//W, 4 INDICES
case WARPRINGNAME: 				//CHAR[32]
case WARPRINGDMAP:				//W, 9 INDICES
case WARPRINGSCREEN:				//W, 9 INDICES
case WARPRINGSIZE:				//C
case CHEATFLAGS:				//W
case CHEATCODELV1:				//CHAR[41], LET'S USE A DIRECT STRING?
case CHEATCODELV2:				//CHAR[41], LET'S USE A DIRECT STRING?
case CHEATCODELV3:				//CHAR[41], LET'S USE A DIRECT STRING?
case CHEATCODELV4:				//CHAR[41], LET'S USE A DIRECT STRING?
	
case PALCYCLEFIRST:				//C
case PALCYCLECOUNT:				//C
case PALCYCLESPEED:				//C

case ZCTUNETITLE:				//CHAR[36]
case ZCTUNESTART:				//LONG
case ZCTUNELOOPSTART:				//LONG
case ZCTUNELOOPEND:				//LONG
case ZCTUNELOOP:				//SHORT
case ZCTUNEVOLUME:				//SHORT
case ZCTUNEFLAGS:				//C
case ZCTUNEFORMAT:				//C --READ ONLY IS PROBABLY BEST

case GAMEQUESTVERSION:			//CHAR[9]
case GAMEQUESTTITLE:				//CHAR[65]

case ZCOLOURTEXT:				//C
case ZCOLOURCAPTION:				//C
case ZCOLOUROVERWORLDBG:			//C
case ZCOLOURDUNGEONBG:			//C
case ZCOLOURDUNGEONFG:			//C
case ZCOLOURCAVEFG:				//C
case ZCOLOURBSDARK:				//C
case ZCOLOURBSGOAL:				//C
case ZCOLOURCOMPASSLIGHT:			//C
case ZCOLOURCOMPASSDARK:		//C
case ZCOLOURSUBSCREENBG:			//C
case ZCOLOURSUBSCREENSHADOW:			//C
case ZCOLOURTRIFRAME:				//C
case ZCOLOURBIGMAPBG:				//C
case ZCOLOURBIGMAPFG:				//C
case ZCOLOURLINKDOT:				//C
case ZCOLOURTRIFORCECSET:			//C
case ZCOLOURTRIFRAMECSET:			//C
case ZCOLOUROVERWORLDMAPCSET:			//C
case ZCOLOURDUNGEONMAPCSET:			//C
case ZCOLOURBLUEFRAMECSET:			//C
case ZCOLOURTRIFORCETILE:			//W
case ZCOLOURTRIFRAMETILE:			//W
case ZCOLOUROVERWORLDMAPTILE:			//W
case ZCOLOURDUNGEONMAPTILE:			//W
case ZCOLOURBLUEFRAMETILE:			//W
case ZCOLOURHCPIECETILE:			//W
case ZCOLOURHCPIECECSET:			//C
case ZCOLOURMSGTEXT:				//C
case ZCOLOURFOO:				//C, 6 INDICES
case ZCOLOURFOO2:				//C, 256 INDICES