/* Allegro datafile object indexes, produced by grabber v4.2.2, MacOS X */
/* Datafile: /zc/trunk/output/common/sfx.dat */
/* Date: Sun Feb  6 19:53:24 2011 */
/* Do not hand edit! */

#define _SIGNATURE                       0        /* DATA */
#define WAV_ARROW                        1        /* SAMP */
#define WAV_BEAM                         2        /* SAMP */
#define WAV_BOMB                         3        /* SAMP */
#define WAV_BRANG                        4        /* SAMP */
#define WAV_CHIME                        5        /* SAMP */
#define WAV_CHINK                        6        /* SAMP */
#define WAV_CLEARED                      7        /* SAMP */
#define WAV_DODONGO                      8        /* SAMP */
#define WAV_DOOR                         9        /* SAMP */
#define WAV_EDEAD                        10       /* SAMP */
#define WAV_EHIT                         11       /* SAMP */
#define WAV_ER                           12       /* SAMP */
#define WAV_FIRE                         13       /* SAMP */
#define WAV_GANON                        14       /* SAMP */
#define WAV_GASP                         15       /* SAMP */
#define WAV_HAMMER                       16       /* SAMP */
#define WAV_HOOKSHOT                     17       /* SAMP */
#define WAV_MSG                          18       /* SAMP */
#define WAV_OUCH                         19       /* SAMP */
#define WAV_PICKUP                       20       /* SAMP */
#define WAV_PLACE                        21       /* SAMP */
#define WAV_PLINK                        22       /* SAMP */
#define WAV_REFILL                       23       /* SAMP */
#define WAV_ROAR                         24       /* SAMP */
#define WAV_SCALE                        25       /* SAMP */
#define WAV_SEA                          26       /* SAMP */
#define WAV_SECRET                       27       /* SAMP */
#define WAV_SPIRAL                       28       /* SAMP */
#define WAV_STAIRS                       29       /* SAMP */
#define WAV_SWORD                        30       /* SAMP */
#define WAV_VADER                        31       /* SAMP */
#define WAV_WAND                         32       /* SAMP */
#define WAV_WHISTLE                      33       /* SAMP */
#define WAV_ZELDA                        34       /* SAMP */
#define WAV_ZN1CHARGE                    35       /* SAMP */
#define WAV_ZN1CHARGE2                   36       /* SAMP */
#define WAV_ZN1DIVINEFIRE                  37       /* SAMP */
#define WAV_ZN1FALL                      38       /* SAMP */
#define WAV_ZN1DIVINEESCAPE               39       /* SAMP */
#define WAV_ZN1FIREBALL                  40       /* SAMP */
#define WAV_ZN1GRASSCUT                  41       /* SAMP */
#define WAV_ZN1HAMMERPOST                42       /* SAMP */
#define WAV_ZN1HOVER                     43       /* SAMP */
#define WAV_ZN1ICE                       44       /* SAMP */
#define WAV_ZN1JUMP                      45       /* SAMP */
#define WAV_ZN1LENSOFF                   46       /* SAMP */
#define WAV_ZN1LENSON                    47       /* SAMP */
#define WAV_ZN1DIVINEPROTECTION1               48       /* SAMP */
#define WAV_ZN1DIVINEPROTECTION2               49       /* SAMP */
#define WAV_ZN1PUSHBLOCK                 50       /* SAMP */
#define WAV_ZN1ROCK                      51       /* SAMP */
#define WAV_ZN1ROCKETDOWN                52       /* SAMP */
#define WAV_ZN1ROCKETUP                  53       /* SAMP */
#define WAV_ZN1SPINATTACK                54       /* SAMP */
#define WAV_ZN1SPLASH                    55       /* SAMP */
#define WAV_ZN1SUMMON                    56       /* SAMP */
#define WAV_ZN1TAP                       57       /* SAMP */
#define WAV_ZN1TAP2                      58       /* SAMP */
#define WAV_ZN1WHIRLWIND                 59       /* SAMP */
#define WAV_ZN2CANE                      60       /* SAMP */
#define Z35                              61       /* SAMP */

