#ifndef ZQ_HOTKEY_H_
#define ZQ_HOTKEY_H_

#include "allegro/gui.h"
#include "base/general.h"

struct Hotkey;

enum
{
	ZQKEY_NULL_KEY,
	ZQKEY_UNDO,
	ZQKEY_REDO,
	ZQKEY_MINUS_FLAG,
	ZQKEY_PLUS_FLAG,
	ZQKEY_SAVE,
	ZQKEY_SAVEAS,
	ZQKEY_OPEN,
	ZQKEY_SCREEN_PAL,
	ZQKEY_SECRET_COMBO,
	ZQKEY_DOORS,
	ZQKEY_FFCS,
	ZQKEY_FLAGS,
	ZQKEY_SCRDATA,
	ZQKEY_TILEWARP,
	ZQKEY_SIDEWARP,
	ZQKEY_LAYERS,
	ZQKEY_RESET_TRANSP,
	ZQKEY_COPY,
	ZQKEY_TOGGLE_DARK,
	ZQKEY_ENEMIES,
	ZQKEY_SHOW_FLAGS,
	ZQKEY_SHOW_FFCS,
	ZQKEY_ITEMS,
	ZQKEY_COMBOS,
	ZQKEY_DARK_PREVIEW,
	ZQKEY_SHOW_INFO,
	ZQKEY_DRAWING_MODE,
	ZQKEY_GOTO_PAGE,
	ZQKEY_SHOW_CMB_CS_INFO,
	ZQKEY_STRINGS,
	ZQKEY_ROOM,
	ZQKEY_TILES,
	ZQKEY_PASTE,
	ZQKEY_PASTEALL,
	ZQKEY_PASTETOALL,
	ZQKEY_PASTEALLTOALL,
	ZQKEY_SHOW_SOLID,
	ZQKEY_PREV_MODE,
	ZQKEY_COMPILE_ZSCRIPT,
	ZQKEY_SCREENSHOT,
	ZQKEY_ABOUT,
	ZQKEY_MINUS_MAP,
	ZQKEY_PLUS_MAP,
	ZQKEY_MINUS_COLOR,
	ZQKEY_PLUS_COLOR,
	ZQKEY_MINUS_SCR_PAL,
	ZQKEY_PLUS_SCR_PAL,
	ZQKEY_MINUS_16_SCR_PAL,
	ZQKEY_PLUS_16_SCR_PAL,
	ZQKEY_SCREEN_ZOOM_IN,
	ZQKEY_SCREEN_ZOOM_OUT,
	ZQKEY_GRID,
	ZQKEY_GRID_COLOR,
	ZQKEY_CHANGE_ALIAS_ORIGIN,
	ZQKEY_DELETE,
	ZQKEY_FULLSCREEN,
	ZQKEY_LYR_0,ZQKEY_LYR_1,ZQKEY_LYR_2,ZQKEY_LYR_3,
	ZQKEY_LYR_4,ZQKEY_LYR_5,ZQKEY_LYR_6,
	ZQKEY_SCR_LPAL_0,ZQKEY_SCR_LPAL_1,ZQKEY_SCR_LPAL_2,ZQKEY_SCR_LPAL_3,
	ZQKEY_SCR_LPAL_4,ZQKEY_SCR_LPAL_5,ZQKEY_SCR_LPAL_6,ZQKEY_SCR_LPAL_7,
	ZQKEY_SCR_LPAL_8,ZQKEY_SCR_LPAL_9,ZQKEY_SCR_LPAL_10,ZQKEY_SCR_LPAL_11,
	ZQKEY_SCR_LPAL_12,ZQKEY_SCR_LPAL_13,ZQKEY_SCR_LPAL_14,ZQKEY_SCR_LPAL_15,
	ZQKEY_SCROLL_SCREEN_UP,ZQKEY_SCROLL_SCREEN_DOWN,ZQKEY_SCROLL_SCREEN_LEFT,ZQKEY_SCROLL_SCREEN_RIGHT,
	ZQKEY_WARP_SCREEN_UP,ZQKEY_WARP_SCREEN_DOWN,ZQKEY_WARP_SCREEN_LEFT,ZQKEY_WARP_SCREEN_RIGHT,
	ZQKEY_SCROLL_COMBO_UP,ZQKEY_SCROLL_COMBO_DOWN,ZQKEY_SCROLL_COMBO_LEFT,ZQKEY_SCROLL_COMBO_RIGHT,
	ZQKEY_COMBO_PAGEUP,ZQKEY_COMBO_PAGEDN,
	ZQKEY_SQUAREPANEL_UP,ZQKEY_SQUAREPANEL_DOWN,
	ZQKEY_TESTMODE,
	ZQKEY_CAUTO_HEIGHTMINUS, ZQKEY_CAUTO_HEIGHTPLUS,
	ZQKEY_CURR_LAYER_HL, ZQKEY_VIEW_MAP,
	ZQKEY_DRAWMODE_NORMAL, ZQKEY_DRAWMODE_ALIAS, ZQKEY_DRAWMODE_POOL, ZQKEY_DRAWMODE_AUTO,
	ZQKEY_IMPORT_COMBOS, ZQKEY_EXPORT_COMBOS,
	ZQKEY_IMPORT_DMAPS, ZQKEY_EXPORT_DMAPS,
	ZQKEY_IMPORT_ZGP, ZQKEY_EXPORT_ZGP,
	ZQKEY_IMPORT_MAP, ZQKEY_EXPORT_MAP,
	ZQKEY_IMPORT_PALS, ZQKEY_EXPORT_PALS,
	ZQKEY_IMPORT_STRINGS, ZQKEY_EXPORT_STRINGS,
	ZQKEY_IMPORT_TILES, ZQKEY_EXPORT_TILES,
	
	ZQKEY_CHANGE_TRACK,
	ZQKEY_CHEATS,
	ZQKEY_CSET_FIX,
	ZQKEY_ALIASES,
	ZQKEY_CMBPOOLS,
	ZQKEY_AUTOCMB,
	ZQKEY_DEFAULT_COMBOS,
	ZQKEY_DELETE_MAP,
	ZQKEY_DMAPS,
	ZQKEY_MAPS,
	ZQKEY_DOOR_COMBO_SETS,
	ZQKEY_PASTE_DOORS,
	ZQKEY_ENDSTRING,
	ZQKEY_EDIT_ENEMIES,
	ZQKEY_DEFAULT_ENEMIES,
	ZQKEY_PASTE_ENEMIES,
	ZQKEY_EXIT,
	ZQKEY_PASTE_FFCS,
	ZQKEY_GAME_ICONS,
	ZQKEY_GOTO_MAP,
	ZQKEY_PASTE_GUY_STR,
	ZQKEY_HEADER,
	ZQKEY_INFO_TYPES,
	ZQKEY_INIT_DATA,
	ZQKEY_INTEG_CHECK_ALL,
	ZQKEY_INTEG_CHECK_SCREENS,
	ZQKEY_INTEG_CHECK_WARPS,
	ZQKEY_EDIT_ITEMS,
	ZQKEY_PASTE_LAYERS,
	ZQKEY_PALETTES_LEVEL,
	ZQKEY_HERO_SPRITE,
	ZQKEY_USED_COMBOS,
	ZQKEY_PALETTES_MAIN,
	ZQKEY_DEFAULT_MAP_STYLES,
	ZQKEY_MAP_STYLES,
	ZQKEY_MIDIS,
	ZQKEY_MISC_COLORS,
	ZQKEY_NEW,
	ZQKEY_OPTIONS,
	ZQKEY_DEFAULT_PALETTES,
	ZQKEY_MAZE_PATH,
	ZQKEY_PLAY_MUSIC,
	ZQKEY_APPLY_TEMPLATE_ALL,
	ZQKEY_REVERT,
	ZQKEY_PASTE_ROOMTYPE,
	ZQKEY_PASTE_SCREEN_DATA,
	ZQKEY_PASTE_SECRET_COMBOS,
	ZQKEY_SFX,
	ZQKEY_SHOP_TYPES,
	ZQKEY_PALETTES_SPRITES,
	ZQKEY_DEFAULT_SPRITE_DATA,
	ZQKEY_STOP_TUNES,
	ZQKEY_EDIT_SUBSCREENS,
	ZQKEY_AMBIENT_MUSIC,
	ZQKEY_NES_DUNGEON_TEMPL,
	ZQKEY_DEFAULT_TILES,
	ZQKEY_MCGUFFIN_PIECES,
	ZQKEY_UNDERCOMBO,
	ZQKEY_PASTE_UNDERCOMBO,
	ZQKEY_VIDEO_MODE,
	ZQKEY_VIEW_PALETTE,
	ZQKEY_VIEW_PIC,
	ZQKEY_PASTE_WARP_RET,
	ZQKEY_WARP_RINGS,
	ZQKEY_PASTE_WARPS,
	ZQKEY_EDIT_SPRITE_DATA,
	ZQKEY_SHOW_CSETS,
	ZQKEY_SHOW_TYPES,
	ZQKEY_DEFAULT_ITEMS,
	ZQKEY_EDIT_DROPSETS,
	ZQKEY_PASTE_PALETTE,
	ZQKEY_QUEST_RULES,
	ZQKEY_REPORT_COMBO_LOC,
	ZQKEY_REPORT_TYPE_LOC,
	ZQKEY_REPORT_ENEMY_LOC,
	ZQKEY_REPORT_ITEM_LOC,
	ZQKEY_REPORT_SCRIPT_LOC,
	ZQKEY_REPORT_LINKS_HERE,
	ZQKEY_CLEAR_QST_PATH,
	ZQKEY_BUGGY_NEXT,
	ZQKEY_RULES_ZSCRIPT,
	ZQKEY_RULES_COMPILER,
	ZQKEY_EDIT_SCREEN_SCRIPT,
	ZQKEY_SCREEN_SCREENSHOT,
	ZQKEY_VIEW_L2_BG,
	ZQKEY_VIEW_L3_BG,
	ZQKEY_BOTTLE_TYPES,
	ZQKEY_BOTTLE_SHOP_TYPES,
	ZQKEY_FIX_WATER_SOLID,
	ZQKEY_FIX_EFFECT_SQUARE,
	ZQKEY_SEARCH_QRS,
	ZQKEY_COMPILE_QUICK,
	ZQKEY_RULESETS,
	ZQKEY_RULETMPLS,
	ZQKEY_COMPILE_SMART,
	
	ZQKEY_DEBUG_CONSOLE,
	ZQKEY_SHOW_HOTKEYS,
	ZQKEY_BIND_HOTKEYS,
	
	ZQKEY_SCREEN_NOTES,
	ZQKEY_BROWSE_SCREEN_NOTES,

	// Note: when adding a new hotkey, categorize in proper group in `render_hotkeys.cpp`.
	ZQKEY_MAX
};
extern Hotkey zq_hotkeys[ZQKEY_MAX];
extern uint favorite_commands[MAXFAVORITECOMMANDS];
char const* get_hotkey_name(uint hkey);
char const* get_hotkey_cfg_name(uint hkey);
char const* get_hotkey_helptext(uint hkey);

void show_hotkey_info(uint hkey);

int run_hotkey(uint hkey);

bool is_reserved_key(int c);
bool is_reserved_keycombo(int c, int modflag);
void default_hotkeys();
void load_hotkeys();
int d_zq_hotkey_proc(int msg, DIALOG* d, int c);
int do_zq_hotkey_dialog();
int do_zq_list_hotkeys_dialog();
optional<uint> select_fav_command();
void write_fav_command(uint ind, uint hkey);

void disable_hotkey(uint hkey, bool dis);
bool disabled_hotkey(uint hkey);

bool selected_hotkey(uint hkey);

#endif

