name: compare

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  PYTHONUNBUFFERED: '1'

jobs:
  compare:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4
        with:
          # Need history to find baseline commit.
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          cache: pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup Node.js (for Surge)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate compare report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          REPLAY_FAILURE_DISCORD_WEBHOOK: ${{ secrets.REPLAY_FAILURE_DISCORD_WEBHOOK }}
        run: >
          bash .github/workflows/run_python.sh .github/workflows/ci.py compare-replays
          --repo ${{ github.repository }}
          --run-id ${{ github.event.workflow_run.id }}
          --ref-name "${{ github.event.workflow_run.head_branch }}"
          --actor "${{ github.actor }}"

      # Upload as artifact, so that if publishing to surge fails the report is still accessible.
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: ${{ github.workspace }}/tests/compare-report
